branch-defaults:
  master:
    environment: django-env
    group_suffix: null
global:
  application_name: django-syn
  branch: null
  default_ec2_keyname: cky_key_pair
  default_platform: python3.4
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
